id = "codeowners"
name = "CODEOWNERS"
description = "CODEOWNERS extension for the Zed editor"
version = "0.1.0"
schema_version = 1
authors = ["Evgenii Gorodilov <jarith@fastmail.de>"]
repository = "https://github.com/jarith/zed-codeowners"
